### ISSUE TITLE
rewrite chat_message.js and chat_history.js to Angular style

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/jabber-firefox-os#29] opened 2014-09-28 21:57 UTC

**Comment by AVGP** [comment] 2014-09-29 20:24
Isn't this a duplicate of #30?

**Comment by MichaelKohler** [comment] 2014-09-29 20:29
well, I splitted the code and tests into separate issues. But I guess we need to do them at them same time anyway ;)

**Closed as completed** 2014-09-30 01:57 UTC
